server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 127.0.0.1
    port: 6379

    maxIdle: 100
    maxTotal: 300
    maxWait: 10000
    testOnBorrow: true
    thetimeout: 100000
    limit: 10

  kafka:
    bootstrap-servers: hadoop102:9092,hadoop103:9092,hadoop104:9092
    consumer:
      group-id: seckill
    template:
      default-topic: seckill_topic
    listener:
      concurrency: 5